apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    name: result-deployment
    app: result-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: result-app-pod
      app: demo-voting-pod
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: demo-voting-pod
    spec:
      containers:
        - name: result-app-pod
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80