apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: nginx
    type: loadbalancer

spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
      - containerPort: 80
        hostPort: 1001
