apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: rc_app
    type: load

spec:
  template: # design the pod here
    metadata:
      name: nginxpod
      labels:
        app: nginx
        type: loadBalancer
    spec:
      containers:
        - name: nginxpod
          image: nginx
  replicas: 3